name: dio_logger
description: Simple logging library for DIO requests. Prints request and response information to a console.
version: 4.0.8+8
repository: https://github.com/Defuera/dio_logger

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
