name: dio_logger
description: Simple logging library for DIO requests
version: 3.0.9+2
repository: https://github.com/Defuera/dio_logger

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
