name: dio_logger
description: Simple logging library for DIO requests. Prints request and response information to a console.
version: 3.0.9+5
repository: https://github.com/Defuera/dio_logger

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.9
